### ISSUE TITLE
Upgrade to React 15.5

### ISSUE THREAD

**Issue by jwineman** [cloudflare/cloudflare-plugin-frontend#117]
https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

**Comment by terinjokes** [comment]
BUT THINK ABOUT ALL THE DEPRECATION WARNINGS

**Comment by thellimist** [comment]
Should we ignore this version? If I didn't miss anything it doesn't seem to provide much value. It's mostly just refactoring a bunch of stuff which already works 😄

**Comment by sejoker** [comment]
React could release migration to Rollup before 16 version. There is no urgency, although I recommend keep up to date with React latest. We probably should wait couple of week before all the upstream dependencies update to `prop-types` like [cf-ui](https://github.com/cloudflare/cf-ui/pull/172)

**Comment by jwineman** [comment]
This will be a very minor upgrade for us.  I'll probably get to it this weekend.  I want to make sure we're upgraded before 16 comes out.

**Comment by jwineman** [comment]
https://github.com/cloudflare/cloudflare-plugin-frontend/pull/125

**Comment by jwineman** [comment]
Still waiting on react-intl and react-select to upgrade to 15.5.

**Comment by thellimist** [comment]
@jwineman https://github.com/yahoo/react-intl/pull/918#issuecomment-296119414 has merged.

**Comment by jwineman** [comment]
Yeah he said he'll release within the next week.

**Comment by MichaelDeBoey** [comment]
`react-intl v2.3.0` is [released](https://github.com/yahoo/react-intl/pull/940) 🙂

**Comment by jwineman** [comment]
https://github.com/cloudflare/cloudflare-plugin-frontend/pull/127

**Comment by jwineman** [comment]
https://github.com/cloudflare/cf-ui/pull/200

**Comment by jwineman** [comment]
https://github.com/cloudflare/cloudflare-plugin-frontend/pull/128

The next warning is from `cf-component-heading`.  We can't upgrade to the react 15.5 because the latest version was migrated to Fela.  I'm considering copying the component locally and upgrading it to use `propTypes` until we have a chance to migrate the rest of the code base to Fela.

**Comment by manatarms** [comment]
Closing this out. Plan is to go to 16 if we can.
