### ISSUE TITLE
We don't trim user email and api key

### ISSUE THREAD

**Issue by thellimist** [cloudflare/cloudflare-plugin-frontend#129]
**v4 Login**
https://github.com/cloudflare/cloudflare-plugin-frontend/blob/master/src/actions/user.js#L73
https://github.com/cloudflare/cloudflare-plugin-frontend/blob/master/src/utils/PluginAPI/PluginAPI.js#L29

**Host API Create**
https://github.com/cloudflare/cloudflare-plugin-frontend/blob/master/src/actions/user.js#L111
https://github.com/cloudflare/cloudflare-plugin-frontend/blob/master/src/utils/CFHostAPI/CFHostAPI.js#L62

I've checked purge cache by url and we do trim in that case. I don't recall any other input which would need trimming

It makes more sense to add it to frontend since we'll have this problem in all plugins.

**Comment by jwineman** [comment]
Is this a bug or an improvement?

**Comment by thellimist** [comment]
Both 😁 

It's low priority since users can make this mistake. In fact they did it and reached out to us.

**Comment by jwineman** [comment]
Yeah that was what I was getting at, I was curious if anyone reported this.
